### ISSUE TITLE
`docker-compose -f docker-compose.yml.backup up --build` is failing at MarkupSafe==1.0 

### ISSUE THREAD

**Issue by isinghmitesh** [gdobrasnki/project_52#7]
https://github.com/gdobrasnki/project_52/blob/a621730af7333f3c5fab2f96c54f97ce4ec9db1e/requirements.txt#L17

```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-174sgrxc/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-174sgrxc/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-174sgrxc/MarkupSafe/pip-egg-info
         cwd: /tmp/pip-install-174sgrxc/MarkupSafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-174sgrxc/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by isinghmitesh** [comment]
Suggestion: with
MarkupSafe==1.1.1
would build.
